version: "3.8"

services:
  postgres-db:
    image: postgres:12-alpine
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./docker-entrypoint-initdb.d/create_balance_table.sql:/docker-entrypoint-initdb.d/create_balance_table.sql"
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=pswd
  app:
    build:
      context: ./
    image: ifuture_task:app
    volumes:
      - ./:/app
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=pswd
    depends_on: [ postgres-db ]
volumes:
  postgres-data: